# Publish packages
# This workflow affects all our npm packages, so just `layout` for now.
#
#	1. increment the version in package.json
#	2. push the new version to the master branch
#	3. build the project (if applicable)
#	4. publish the project
#	4. update all usages of layout to the latest
#	5. commit and push these changes

# Secrets:
# - NPM_TOKEN: required to publish the new version to NPM

name: publish

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build project
      run: |
        npm ci
        npm run build-bundle --if-present

    - name: Configure git credentials
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Increment project version
      run: npm version patch

    - name: Publish project
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        npm publish --access public
        rm .npmrc

    - name: Commit and push changes
      run: |
        git commit -m "CI: release new el-layout version." -a
        git pull
        git push